import {
  IconBrandReact,
  IconBrandDeno,
  IconBrandJavascript,
  IconBrandCss3,
  IconBrandWordpress,
  IconBrandPhp,
  IconBrandNpm,
  IconBrandGatsby,
  IconBrandFigma,
  IconBrandGoogle,
  IconBrandGmail,
  IconBrandGooglePhotos,
  IconHtml,
  IconSun,
  IconMoon,
  IconDeviceLaptop,
  IconMenu2,
  IconSeo,
  IconX,
  type Icon as TablerIcons,
} from "@tabler/icons-react";

export type Icon = TablerIcons;

export const Icons = {
  react: IconBrandReact,
  docusaurus: IconBrandDeno,
  javascript: IconBrandJavascript,
  html: IconHtml,
  css: IconBrandCss3,
  wordpress: IconBrandWordpress,
  php: IconBrandPhp,
  npm: IconBrandNpm,
  gatsby: IconBrandGatsby,
  figma: IconBrandFigma,
  google: IconBrandGoogle,
  gmail: IconBrandGmail,
  googlePhotos: IconBrandGooglePhotos,
  seo: IconSeo,
  hamburger: IconMenu2,
  close: IconX,
  lightTheme: IconSun,
  darkTheme: IconMoon,
  system: IconDeviceLaptop,
};
